### ISSUE TITLE
Estructura que represente la entidad mínima

### ISSUE THREAD

**Issue by migueorg** [Slowmybrosh/DietApp#17]
Como programador y como parte de [lo que hablamos](https://github.com/Slowmybrosh/DietApp/issues/11#issuecomment-949615630) en el #11, se debería crear una clase que almacenase la información base sobre la que trabajar, en este caso la información nutricional.

Esto avanzaría #16

**Comment by Slowmybrosh** [comment]
Debido al desuso en el posterior desarrollo del proyecto, se debe eliminar el atributo 'id' de la misma; además de modificar el atributo 'kilojulios' pasandolo a 'kilocalorias' dado que son equivalentes, no habrá problemas en el futuro.

Una vez completado este avance, se cerraría #16 completando así el milestone
