### ISSUE TITLE
Cálculo de calorías recomendadas

### ISSUE THREAD

**Issue by Slowmybrosh** [Slowmybrosh/DietApp#28]
Para la creación de la dieta se calcularán primero las calorías recomendadas para el usuario, estas se calculan a partir de los datos del usuario: edad, peso, altura, nivel de actividad, sexo y objetivo de la dieta. 

Este está relacionado con la HU #11

**Comment by JJ** [comment]
La cantidad de calorías es lo que tú le vas a dar. El usuario querrá resolver un problema, o tener algún beneficio. Tú le vas a ofrecer hacerlo calculando las calorías, pero una vez que se las calcules, ¿cómo beneficia al usuario? ¿De qué otra forma podría solucionarse el problema que no has dicho? En resumen: esto es un issue, no una HU. Revisa, por favor, el concepto de HU.
