### ISSUE TITLE
Test para la clase Dieta

### ISSUE THREAD

**Issue by Slowmybrosh** [Slowmybrosh/DietApp#31]
Se deben crear los diversos test para comprobar la creación de la clase Dieta, los getters y que calcula correctamente las calorias recomendadas siguiendo #28

**Comment by JJ** [comment]
Lo que tienes que entender es que los issues son un problema, y por tanto hasta que no escribas el test que indique que se ha resuelto el problema no puedes cerrar el issue. Si entiendes los issues como tareas pasa esto: un issue para hacerla, otra para testearla... Y luego los mensajes de commit, que no explican como resuelven el problema, sino simplemente que se ha hecho la tarea.
